### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by zeleniy** [zeleniy/rDashboard#8]
@rrekapalli how you got that image/pdf?

<img width="858" alt="screen shot 2017-10-22 at 22 29 57" src="https://user-images.githubusercontent.com/2780617/31865533-9be9809a-b778-11e7-81c2-d931f0c0d04a.png">

**Comment by rrekapalli** [comment]
Just Ctrl+P on the browser and then changed the page orientation to landscape and printed it as PDF.  Few more feedback points on the latest version.

![dashboard_feedback](https://user-images.githubusercontent.com/533433/31880655-d0a796a6-b7fe-11e7-8df2-310beaa4041f.png)

**Comment by rrekapalli** [comment]
Looks like we are almost done except for a few more feedback points:

1. Bar Chart needs to be sorted in descending order.  Currently, they are not being sorted when applied a filter. 
2. The Scatterplot, the bubble sizes are not changing according to the change in radio buttons. Also, can we have axis labels for the scatter plot.  x-axis label is "Case Created Dates', and then y-Axis label "Data Source Count".
3. The Color scale should be different for both 'Bar Chart' and 'Pie Chart'.  Currently, it's the same color given to the Heat Map which leads to confusion.
4. Can we have the Legend plotted horizontally below the circle on the Pie Chart?  Since we are not expecting more than 3 or 4 categories, I think it should be fine to display them at the bottom of the circle.  May be, the Legend should also display the values (Percentages).
5. In the tiles, can we have the numbers switched?  I mean, the Size should be on the right and the count of stat should be on the left.  
6. The tooltips on the elements should be anything other than the details that are currently displayed on the charts. For example, the bubble chart should display case name and other case specific details.
7. The Geographic map still doesn't reflect the bubble size according to the filters applied.
8. Applied filters row isn't showing the 'Tile' specific filters.  For example, when I clicked on 'Processed' tile, it's not being shown in the Applied Filters row.  Also, is it possible to show the actual filter that is applied rather than the 'Column name' of the filter.  For example, currently when I clicked on 'Plaintiff' pie of the pie chart, it's displaying the CaseType, could it be 'Plaintiff' rather than the 'CaseType' in the applied filters row?
9. Can we have the 'Filters row always displayed.  Probably, we can have a label "Applied Filters: " and then the actual filters that are applied.

**Comment by rrekapalli** [comment]
One more point:  
10. Can we have one more tile that displays, total cases?  I think currently, the numbers aren't making much sense if we do not have the case count displayed some where. I think, Having one more 'Tile' would be helpful.  But open for suggestions.

**Comment by zeleniy** [comment]
> Can we have one more tile that displays, total cases? I think currently, the numbers aren't making much sense if we do not have the case count displayed some where. I think, Having one more 'Tile' would be helpful. But open for suggestions.

@rrekapalli i have no ideas. We can add one more tile, or simple text somewhere in top.

**Comment by zeleniy** [comment]
Print issue is fixed

**Comment by zeleniy** [comment]
![screen_shot_2017-10-24_at_14_13_10](https://user-images.githubusercontent.com/2780617/31940232-10505956-b8c6-11e7-9831-e0b1c947ef25.jpg)
![screen_shot_2017-10-24_at_14_12_50](https://user-images.githubusercontent.com/2780617/31940235-15808b58-b8c6-11e7-9190-92d71be78c95.jpg)

**Comment by rrekapalli** [comment]
Seems like it's a browser issue.  I am using Microsoft Edge (also tried on Chrome) on Windows 10 which doesn't have this option.  But, will check with other browsers.  Will close this issue for now.
